import { hashSync } from 'bcrypt-ts-edge';
import { Roles } from '@/lib/types/role';

const sampleData = {
  users: [
    {
      name: 'John Doe',
      email: 'admin@example.com',
      password: hashSync('123456'),
      role: Roles.Admin,
    },
    {
      name: 'Jane Doe',
      email: 'user@example.com',
      password: hashSync('123456'),
      role: Roles.User,
    },
    {
      name: 'Alice Johnson',
      email: 'alice@example.com',
      password: hashSync('123456'),
      role: Roles.User,
    },
    {
      name: 'Bob Williams',
      email: 'bob@example.com',
      password: hashSync('123456'),
      role: Roles.User,
    },
    {
      name: 'Charlie Brown',
      email: 'charlie@example.com',
      password: hashSync('123456'),
      role: Roles.User,
    },
    {
      name: 'Diana Prince',
      email: 'diana@example.com',
      password: hashSync('123456'),
      role: Roles.User,
    },
  ],
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banners/banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banners/banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Nike Dri-FIT Running Jacket',
      slug: 'nike-dri-fit-running-jacket',
      category: "Men's Jackets",
      description: 'Lightweight and breathable for high-performance runs',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 129.99,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 22,
      stock: 12,
      isFeatured: true,
      banner: '/images/banners/banner-1.jpg',
    },
    {
      name: 'Adidas Ultraboost Running Shoes',
      slug: 'adidas-ultraboost-running-shoes',
      category: "Men's Shoes",
      description: 'Responsive cushioning for all-day comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 189.99,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 35,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Levi's 501 Original Fit Jeans",
      slug: 'levis-501-original-fit-jeans',
      category: "Men's Jeans",
      description: 'The iconic straight leg jean since 1873',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 69.5,
      brand: "Levi's",
      rating: 4.4,
      numReviews: 28,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Under Armour Tech Polo',
      slug: 'under-armour-tech-polo',
      category: "Men's Polos",
      description: 'Quick-dry fabric with anti-odor technology',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 49.99,
      brand: 'Under Armour',
      rating: 4.3,
      numReviews: 15,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
  ],
  orders: [
    {
      userEmail: 'user@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '123 Main Street',
        city: 'New York',
        postalCode: 10001,
        country: 'United States',
      },
      paymentMethod: 'PayPal' as const,
      isPaid: true,
      paidAt: new Date('2025-12-15T10:30:00'),
      isDelivered: true,
      deliveredAt: new Date('2025-12-20T14:00:00'),
      createdAt: new Date('2025-12-14T09:00:00'),
      items: [
        { productSlug: 'polo-sporting-stretch-shirt', quantity: 2 },
        { productSlug: 'calvin-klein-slim-fit-stretch-shirt', quantity: 1 },
      ],
    },
    {
      userEmail: 'user@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '123 Main Street',
        city: 'New York',
        postalCode: 10001,
        country: 'United States',
      },
      paymentMethod: 'Stripe' as const,
      isPaid: true,
      paidAt: new Date('2026-01-05T11:00:00'),
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-01-04T16:20:00'),
      items: [{ productSlug: 'nike-dri-fit-running-jacket', quantity: 1 }],
    },
    {
      userEmail: 'alice@example.com',
      shippingAddress: {
        addressName: 'Office',
        address: '456 Oak Avenue, Suite 200',
        city: 'Los Angeles',
        postalCode: 90001,
        country: 'United States',
      },
      paymentMethod: 'PayPal' as const,
      isPaid: true,
      paidAt: new Date('2025-11-20T08:45:00'),
      isDelivered: true,
      deliveredAt: new Date('2025-11-25T16:30:00'),
      createdAt: new Date('2025-11-19T14:10:00'),
      items: [
        { productSlug: 'brooks-brothers-long-sleeved-shirt', quantity: 1 },
        { productSlug: 'polo-ralph-lauren-oxford-shirt', quantity: 1 },
        { productSlug: 'polo-classic-pink-hoodie', quantity: 1 },
      ],
    },
    {
      userEmail: 'alice@example.com',
      shippingAddress: {
        addressName: 'Office',
        address: '456 Oak Avenue, Suite 200',
        city: 'Los Angeles',
        postalCode: 90001,
        country: 'United States',
      },
      paymentMethod: 'Stripe' as const,
      isPaid: true,
      paidAt: new Date('2026-01-18T13:20:00'),
      isDelivered: true,
      deliveredAt: new Date('2026-01-23T10:00:00'),
      createdAt: new Date('2026-01-17T20:00:00'),
      items: [{ productSlug: 'adidas-ultraboost-running-shoes', quantity: 1 }],
    },
    {
      userEmail: 'alice@example.com',
      shippingAddress: {
        addressName: 'Office',
        address: '456 Oak Avenue, Suite 200',
        city: 'Los Angeles',
        postalCode: 90001,
        country: 'United States',
      },
      paymentMethod: 'PayPal' as const,
      isPaid: true,
      paidAt: new Date('2026-02-10T09:00:00'),
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-02-09T18:30:00'),
      items: [
        { productSlug: 'under-armour-tech-polo', quantity: 2 },
        { productSlug: 'levis-501-original-fit-jeans', quantity: 1 },
      ],
    },
    {
      userEmail: 'bob@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '789 Pine Road',
        city: 'Chicago',
        postalCode: 60601,
        country: 'United States',
      },
      paymentMethod: 'Cash on Delivery' as const,
      isPaid: false,
      paidAt: undefined,
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-02-20T12:00:00'),
      items: [
        { productSlug: 'tommy-hilfiger-classic-fit-dress-shirt', quantity: 1 },
        { productSlug: 'polo-sporting-stretch-shirt', quantity: 1 },
      ],
    },
    {
      userEmail: 'bob@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '789 Pine Road',
        city: 'Chicago',
        postalCode: 60601,
        country: 'United States',
      },
      paymentMethod: 'Stripe' as const,
      isPaid: true,
      paidAt: new Date('2025-10-10T15:00:00'),
      isDelivered: true,
      deliveredAt: new Date('2025-10-15T11:20:00'),
      createdAt: new Date('2025-10-09T09:45:00'),
      items: [
        { productSlug: 'polo-classic-pink-hoodie', quantity: 2 },
        { productSlug: 'nike-dri-fit-running-jacket', quantity: 1 },
      ],
    },
    {
      userEmail: 'charlie@example.com',
      shippingAddress: {
        addressName: 'Apartment',
        address: '321 Elm Street, Apt 4B',
        city: 'Houston',
        postalCode: 77001,
        country: 'United States',
      },
      paymentMethod: 'PayPal' as const,
      isPaid: true,
      paidAt: new Date('2025-12-28T10:00:00'),
      isDelivered: true,
      deliveredAt: new Date('2026-01-02T09:30:00'),
      createdAt: new Date('2025-12-27T20:15:00'),
      items: [
        { productSlug: 'adidas-ultraboost-running-shoes', quantity: 1 },
        { productSlug: 'levis-501-original-fit-jeans', quantity: 2 },
      ],
    },
    {
      userEmail: 'charlie@example.com',
      shippingAddress: {
        addressName: 'Apartment',
        address: '321 Elm Street, Apt 4B',
        city: 'Houston',
        postalCode: 77001,
        country: 'United States',
      },
      paymentMethod: 'Stripe' as const,
      isPaid: true,
      paidAt: new Date('2026-02-01T14:30:00'),
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-01-31T11:00:00'),
      items: [
        { productSlug: 'calvin-klein-slim-fit-stretch-shirt', quantity: 1 },
        { productSlug: 'under-armour-tech-polo', quantity: 1 },
        { productSlug: 'brooks-brothers-long-sleeved-shirt', quantity: 1 },
      ],
    },
    {
      userEmail: 'charlie@example.com',
      shippingAddress: {
        addressName: 'Apartment',
        address: '321 Elm Street, Apt 4B',
        city: 'Houston',
        postalCode: 77001,
        country: 'United States',
      },
      paymentMethod: 'Cash on Delivery' as const,
      isPaid: false,
      paidAt: undefined,
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-02-22T08:00:00'),
      items: [{ productSlug: 'polo-ralph-lauren-oxford-shirt', quantity: 1 }],
    },
    {
      userEmail: 'diana@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '555 Maple Drive',
        city: 'San Francisco',
        postalCode: 94102,
        country: 'United States',
      },
      paymentMethod: 'PayPal' as const,
      isPaid: true,
      paidAt: new Date('2025-11-05T12:00:00'),
      isDelivered: true,
      deliveredAt: new Date('2025-11-10T15:45:00'),
      createdAt: new Date('2025-11-04T17:30:00'),
      items: [
        { productSlug: 'polo-sporting-stretch-shirt', quantity: 1 },
        { productSlug: 'brooks-brothers-long-sleeved-shirt', quantity: 1 },
        { productSlug: 'tommy-hilfiger-classic-fit-dress-shirt', quantity: 1 },
      ],
    },
    {
      userEmail: 'diana@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '555 Maple Drive',
        city: 'San Francisco',
        postalCode: 94102,
        country: 'United States',
      },
      paymentMethod: 'Stripe' as const,
      isPaid: true,
      paidAt: new Date('2026-01-12T09:15:00'),
      isDelivered: true,
      deliveredAt: new Date('2026-01-17T13:00:00'),
      createdAt: new Date('2026-01-11T21:45:00'),
      items: [
        { productSlug: 'nike-dri-fit-running-jacket', quantity: 1 },
        { productSlug: 'adidas-ultraboost-running-shoes', quantity: 1 },
      ],
    },
    {
      userEmail: 'diana@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '555 Maple Drive',
        city: 'San Francisco',
        postalCode: 94102,
        country: 'United States',
      },
      paymentMethod: 'PayPal' as const,
      isPaid: true,
      paidAt: new Date('2026-02-15T10:30:00'),
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-02-14T14:00:00'),
      items: [
        { productSlug: 'levis-501-original-fit-jeans', quantity: 1 },
        { productSlug: 'under-armour-tech-polo', quantity: 1 },
      ],
    },
    {
      userEmail: 'user@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '123 Main Street',
        city: 'New York',
        postalCode: 10001,
        country: 'United States',
      },
      paymentMethod: 'Cash on Delivery' as const,
      isPaid: false,
      paidAt: undefined,
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-02-21T19:00:00'),
      items: [
        { productSlug: 'adidas-ultraboost-running-shoes', quantity: 1 },
        { productSlug: 'polo-classic-pink-hoodie', quantity: 1 },
        { productSlug: 'levis-501-original-fit-jeans', quantity: 2 },
      ],
    },
    {
      userEmail: 'bob@example.com',
      shippingAddress: {
        addressName: 'Home',
        address: '789 Pine Road',
        city: 'Chicago',
        postalCode: 60601,
        country: 'United States',
      },
      paymentMethod: 'PayPal' as const,
      isPaid: true,
      paidAt: new Date('2026-02-18T11:00:00'),
      isDelivered: false,
      deliveredAt: undefined,
      createdAt: new Date('2026-02-17T15:30:00'),
      items: [
        { productSlug: 'calvin-klein-slim-fit-stretch-shirt', quantity: 2 },
        { productSlug: 'polo-ralph-lauren-oxford-shirt', quantity: 1 },
      ],
    },
  ],
};

export default sampleData;
